version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/sdks/java"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/sdks/python"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
