npmName: "@delopay/sdk-generated"
npmVersion: "0.1.0"
supportsES6: true
withInterfaces: true
useSingleRequestParameter: true
enumPropertyNaming: original
modelPropertyNaming: original
sortParamsByRequiredFlag: true
sortModelPropertiesByRequiredFlag: true
hideGenerationTimestamp: true

